name: CI/CD Pipeline for Databricks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest pyspark pandas matplotlib

      - name: Run tests
        run: pytest tests/

  deploy:
    name: Deploy to Databricks (Dev or Prod Folder)
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          echo -e "${{ secrets.DATABRICKS_HOST }}\n${{ secrets.DATABRICKS_TOKEN }}" | databricks configure --token

      - name: Determine target folder and upload
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"

          if [ "$BRANCH_NAME" = "main" ]; then
            TARGET_PATH="/Shared/Stavanger_parkering_prod"
          else
            TARGET_PATH="/Shared/Stavanger_parkering_dev"
          fi

          databricks workspace import ./notebooks/Stavanger_parkering.ipynb "$TARGET_PATH" -f SOURCE -l PYTHON --overwrite


